### ISSUE TITLE
Exact accuracy percentage scores for annotation prediction task?

### ISSUE THREAD

**Issue by patricks-lab** [HelloWorldLTY/scEval#1]
Thanks for the great work. I was wondering if you have the table of exact numeric accuracy scores (e.g. something from 0% to 100% accuracy, like 0.785) for figure 2e of your paper for each model and dataset (https://www.biorxiv.org/content/10.1101/2023.09.08.555192v3.full.pdf)?
![Screenshot 2023-11-07 at 10 50 24 AM](https://github.com/HelloWorldLTY/scEval/assets/8272305/ea618904-fd1c-48d2-9e1a-744ef3454edc)
 
If possible, I'd also greatly appreciate if you could send the accuracy scores for figure 3a and 3c (for the gene level tasks).
![Screenshot 2023-11-07 at 10 59 19 AM](https://github.com/HelloWorldLTY/scEval/assets/8272305/45e0476c-f4c7-446b-814f-4bec04f4e7c9)

 
Thanks in advance!
-Patrick

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your interests of our work. Would you please give me your email? I can send the specific scores via email through an xlsx file.

**Comment by patricks-lab** [comment]
Yeah sure absolutely, my email is patricky168 at gmail.com Thanks in advance!
