### ISSUE TITLE
Are there any updated benchmarking results on new method (e.g., UCE, Cell PLM)

### ISSUE THREAD

**Issue by mrbeann** [HelloWorldLTY/scEval#4]
Thank you for your awesome work, it seems the results of the novel models are not included in the paper and this repo? Can you kindly provide the results?

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your question. Yes, we did include benchmarking results for new models, summarized in our manuscript: https://www.biorxiv.org/content/10.1101/2023.09.08.555192v5.
