### ISSUE TITLE
Error when setting up a virtual environment

### ISSUE THREAD

**Issue by inhyeoklee** [HelloWorldLTY/scEval#5]
Hello,

Thank you for creating this wonderful benchmarking workflow!

While attempting to set up the virtual environment, I used the command "conda env create -n scgpt --file scgpt_bench.yml"  as recommended. Unfortunately, I encountered some errors related to Python version requirements and the absence of a specific distribution for cmap2d==0.0.1.dev0. The error message is as follows:

```
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.1.8 Requires-Python >=3.9; 0.1.81 Requires-Python >=3.9; ... 0.10.7 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement cmap2d==0.0.1.dev0 (from versions: none)
ERROR: No matching distribution found for cmap2d==0.0.1.dev0

failed

CondaEnvException: Pip failed
```

I would appreciate any advice or suggestions you could offer to help resolve this issue.

Thanks,
Daniel

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your question. I am checking this process and I received a similar error. My suggestion is try to comment this step like:

```
#cmap2d==0.0.1.dev0
```

In total there are three packages you may need to comment:

```
#       - cmap2d==0.0.1.dev0
#       - cscore==0.0.1
#       - destvi-utils==0.1.0
```

You can also delete them if you want.

And then run the installation again. You may also receive other errors/warnings, you can try to comment all of the instructions causing errors and ignore the warnings. Please have a try and let me know if there are further problems. Thanks.

**Comment by HelloWorldLTY** [comment]
Since there is no further reply for >1 week, I plan to close this comment. Feel free to reopen it if you need:)
