### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by caiquanyou** [HelloWorldLTY/scEval#8]
Could you provide the docker or other container image that would be easier for users to evaluate their results?

**Comment by HelloWorldLTY** [comment]
Hi @caiquanyou , thanks for your request. I can try to develop a docker image for loading the metrics, but it might be difficult to have images for every baselines, as our hpc cluster does not have docker. You can visit installation_baselines for details of baselines. I will update to you when I finish.

**Comment by HelloWorldLTY** [comment]
Hi, we now provide a dockerfile for deploying scEval. Please have a try and let me know if you have any problems. The current version requires GPU for running, if you do not have GPU, you can modify the torch version in the scgpt_bench.yml file. Thanks a lot.

**Comment by caiquanyou** [comment]
Thanks for provide the Dockerfile
